version: '3.8'
services:
  data-processor:
    build: .
    stdin_open: true
    tty: true
    environment:
      - MECABRC=/usr/local/etc/mecabrc
      - PORT=8080
      - DEBUG=True
      - OLLAMA_MODEL=qwen2.5-coder:1.5b
    volumes:
      - .:/work
      - ./output_chunks:/output_chunks
      - ${SERVICE_CATALOG_PATH}:/output_json/service_catalog.json
    command: >
      sh -c "
        ollama serve &
        sleep 10 &&
        ollama pull qwen2.5-coder:1.5b &&
        python /work/chunk_sep.py /output_json/service_catalog.json &&
        python -u /work/chunk_serch_webui.py
      "
    ports:
      - "8080:8080"
